//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIF_Builders.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectEquipment
    {
        public int ProjectEquipmentID { get; set; }
        [Display(Name = "Project"), Required]
        public int ProjectID { get; set; }

        [Display(Name = "Equipment"), Required]
        public int EquipmentID { get; set; }

        public virtual Equipment Equipment { get; set; }
        public virtual Project Project { get; set; }
    }
}
